map_publisher:
  ros__parameters:
    ground_truth_topic: "/ground_truth"
    use_sim_time: True

vfh_follower:
  ros__parameters:
    linear_speed: 0.8
    angular_speed_max: 1.0
    robot_radius: 0.5
    safety_radius: 0.8
    use_sim_time: True