# Waypoint publisher specific parameters
waypoint_publisher:
  ros__parameters:
    frame_id: "odom"
    # waypoints_x:   [-3.78, -2.03, 0.78,   3.08,   5.30]
    # waypoints_y:   [2.00,  -2.08, 2.54,   -2.6,   2.13]
    # waypoints_yaw: [45.0,  39.29, -43.81, -20.89, 125.21]

    waypoints_x:   [0.6,  2.00]
    waypoints_y:   [0.00,  0.00]
    waypoints_yaw: [45.0,  -2.74]
    use_sim_time: False

# map_publisher:
#   ros__parameters:
#     ground_truth_topic: "/odom"
#     use_sim_time: False

vfh_follower:
  ros__parameters:
    linear_speed: 0.20
    angular_speed_max: 1.0
    robot_radius: 0.25
    safety_radius: 0.25
    ground_truth_topic: "/odom"
    laser_scan_topic: "/scan"
    use_sim_time: False