# Waypoint publisher specific parameters
waypoint_publisher:
  ros__parameters:
    frame_id: "map"
    world_name: "polkadot"
    #Easy waypoints
    # waypoints_x:   [-3.78, -2.03, 0.78,   3.08,   5.30]
    # waypoints_y:   [2.00,  -2.08, 2.54,   -2.6,   2.13]
    # waypoints_yaw: [45.0,  39.29, -43.81, -20.89, 125.21]

    #Hard waypoints
    waypoints_x:   [-2.65,  0.00,  2.89,   6.02]
    waypoints_y:   [6.52,   0.03, 6.54,   0.28]
    waypoints_yaw: [-80.09,  -2.74, -96.31, -156.47]

    use_sim_time: True

map_publisher:
  ros__parameters:
    ground_truth_topic: "/ground_truth"
    use_sim_time: True

vfh_follower:
  ros__parameters:
    linear_speed: 1.0
    angular_speed_max: 1.0
    use_sim_time: True